name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-license
        run: cargo install cargo-license
      - name: Check licenses
        run: cargo license --json | jq '.[] | select(.license | test("GPL|AGPL|LGPL") | not)'